version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  fluentbit:
    image: fluent/fluent-bit:1.8
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
    volumes:
      - ./fluentbit:/fluent-bit/etc

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
